name: CI/CD Pipeline for MLOps FastAPI

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-push-docker-image:
    runs-on: self-hosted # <--- ubuntu-latest 에서 self-hosted 로 변경!!

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Docker 캐시 기능 등을 활용하기 위해 Buildx 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # GitHub Secrets에 등록된 ID/PW를 이용해 Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Docker 이미지 빌드 및 Docker Hub 푸시
      # latest 태그와 함께 github commit SHA를 태그로 같이 추가하여 버전 관리 수행
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mlops-financial-analysis:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/mlops-financial-analysis:${{ github.sha }}
          # 빌드 시간 단축을 위한 GitHub Actions 기반 캐시 사용
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 기존에 실행중인 컨테이너가 있다면 강제로 삭제하여 포트 8000 충돌 방지
      - name: Stop and Remove Existing Container
        run: |
          if (docker ps -a -q -f name=^fastapi-mlops$) {
              docker rm -f fastapi-mlops
          }
        shell: powershell

      # Docker Hub에 업로드된 최신 이미지를 가져와 백그라운드(-d) 컨테이너로 띄우기
      - name: Run New Container
        run: docker run -d --restart unless-stopped --name fastapi-mlops -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/mlops-financial-analysis:latest
        shell: powershell
